
export interface Regency {
    name: string;
    districts: string[];
}

export interface Province {
    name: string;
    regencies: Regency[];
}

export const kalimantanData: Province[] = [
    {
        name: "KALIMANTAN SELATAN",
        regencies: [
            {
                name: "KOTA BANJARMASIN",
                districts: ["BANJARMASIN BARAT", "BANJARMASIN SELATAN", "BANJARMASIN TENGAH", "BANJARMASIN TIMUR", "BANJARMASIN UTARA"]
            },
            {
                name: "KOTA BANJARBARU",
                districts: ["BANJARBARU SELATAN", "BANJARBARU UTARA", "CEMPAKA", "LANDASAN ULIN", "LIANG ANGGANG"]
            },
            { name: "KAB. BALANGAN", districts: ["AWAYAN", "BATU MANDI", "HALONG", "JUAI", "LAMPIHONG", "PARINGIN", "PARINGIN SELATAN", "TEBING TINGGI"] },
            { name: "KAB. BANJAR", districts: ["ALUH-ALUH", "ARANIO", "BERUNTUNG BARU", "GAMBUT", "KARANG INTAN", "KERTAK HANYAR", "MARTAPURA", "MARTAPURA BARAT", "MARTAPURA TIMUR", "MATARAMAN", "PENGARON", "PARAMASAN", "SAMBUNG MAKMUR", "SEI PINANG", "SEI TABUK", "SIMPANG EMPAT", "TATAH MAKMUR", "TELAGA BAUNTUNG", "CINTAPURI DARUSSALAM"] },
            { name: "KAB. BARITO KUALA", districts: ["ALALAK", "ANJIR MUARA", "ANJIR PASAR", "BAKUMPAI", "BARAMBAI", "BELAWANG", "CERBON", "JEJANGKIT", "KURIPAN", "MANDASTANA", "MARABAHAN", "MEKARSARI", "RANTAU BADAUH", "TABUNGANEN", "TAMBAN", "WANARAYA", "TABUKAN"] },
            { name: "KAB. HULU SUNGAI SELATAN", districts: ["ANGKINANG", "DAHA BARAT", "DAHA SELATAN", "DAHA UTARA", "KALUMPANG", "KANDANGAN", "LINGKARAN", "PADANG BATUNG", "SIMPUR", "SUNGAI RAYA", "TELAGA LANGSAT"] },
            { name: "KAB. HULU SUNGAI TENGAH", districts: ["BARABAI", "BATANG ALAI SELATAN", "BATANG ALAI TIMUR", "BATANG ALAI UTARA", "BATU BENAWA", "HANTAKAN", "HARUYAN", "LABUAN AMAS SELATAN", "LABUAN AMAS UTARA", "LIMPASU", "PANDAWAN"] },
            { name: "KAB. HULU SUNGAI UTARA", districts: ["AMUNTAI BARAT", "AMUNTAI SELATAN", "AMUNTAI TENGAH", "AMUNTAI UTARA", "BABIRIK", "BANJANG", "DANAU PANGGANG", "HAUR GADING", "PAMINGGIR", "SUNGAI PANDAN", "SUNGAI TABUKAN"] },
            { name: "KAB. KOTABARU", districts: ["HAMPARAN PERAK", "KELUMPANG BARAT", "KELUMPANG HILIR", "KELUMPANG HULU", "KELUMPANG SELATAN", "KELUMPANG TENGAH", "KELUMPANG UTARA", "PAMUKAN BARAT", "PAMUKAN SELATAN", "PAMUKAN UTARA", "PULAU LAUT BARAT", "PULAU LAUT KEPULAUAN", "PULAU LAUT SELATAN", "PULAU LAUT TANJUNG SELAYAR", "PULAU LAUT TENGAH", "PULAU LAUT TIMUR", "PULAU LAUT UTARA", "PULAU SEBUKU", "PULAU SEMBILAN", "SAMPANAHAN", "SUNGAI DURIAN"] },
            { name: "KAB. TABALONG", districts: ["BANUA LAWAS", "BINTANG ARA", "HARUAI", "JARO", "KELUA", "MUARA HARUS", "MUARA UYA", "MURUNG PUDAK", "Pugaan", "TANJUNG", "TANTA", "UPAU"] },
            { name: "KAB. TANAH BUMBU", districts: ["ANGSANA", "BATU LICIN", "KARANG BINTANG", "KURANJI", "KUSAN HILIR", "KUSAN HULU", "MANTEWE", "SATUI", "SIMPANG EMPAT", "SUNGAI LOBAN"] },
            { name: "KAB. TANAH LAUT", districts: ["BAJUIN", "BATI-BATI", "BUMI MAKMUR", "JORONG", "KINTAP", "KURAU", "PANYIPATAN", "PELAIHARI", "TAKISUNG", "TAMBANG ULANG", "BATU AMPAR"] },
            { name: "KAB. TAPIN", districts: ["BAKARANGAN", "BUNGUR", "CANDI LARAS SELATAN", "CANDI LARAS UTARA", "HATUNGUN", "LOKPAIKAT", "PIANI", "SALAM BABARIS", "TAPIN SELATAN", "TAPIN TENGAH", "TAPIN UTARA", "BINUANG"] },
        ]
    },
    {
        name: "KALIMANTAN TENGAH",
        regencies: [
            { name: "KOTA PALANGKARAYA", districts: ["BUKIT BATU", "JEKAN RAYA", "PAHANDUT", "RAKUMPIT", "SEBANGAU"] },
            { name: "KAB. BARITO SELATAN", districts: ["AWANG", "BENUA LIMA", "DUSUN HILIR", "DUSUN SELATAN", "DUSUN UTARA", "GUNUNG BINTANG AWAI", "KARAU KUALA", "PEMATANG KARAU"] },
            { name: "KAB. BARITO TIMUR", districts: ["AWANG", "BENUA LIMA", "DUSUN TENGAH", "DUSUN TIMUR", "KARUSEN JANANG", "PAJU EPAT", "PAKU", "PEMATANG KARAU", "RAREN BATUAH"] },
            { name: "KAB. BARITO UTARA", districts: ["GUNUNG PUREI", "GUNUNG TIMANG", "LAHEI", "LAHEI BARAT", "MONTALLAT", "TEWEH BARU", "TEWEH SELATAN", "TEWEH TENGAH", "TEWEH TIMUR"] },
            { name: "KAB. GUNUNG MAS", districts: ["DAMANG BATU", "KAHAYAN HULU UTARA", "KURUN", "MANUHING", "MANUHING RAYA", "MIHING RAYA", "RUNGAN", "RUNGAN BARAT", "RUNGAN HULU", "SEPANG", "TEWAH"] },
            { name: "KAB. KAPUAS", districts: ["BASARANG", "BATAGUH", "DADAHUP", "KAPUAS BARAT", "KAPUAS HILIR", "KAPUAS KUALA", "KAPUAS MURUNG", "KAPUAS TENGAH", "KAPUAS TIMUR", "MANTANGAI", "PASAK TALAWANG", "PULAU PETAK", "SELAT", "TAMBAN CATUR", "TIMPAH", "Mandau Talawang"] },
            { name: "KAB. KATINGAN", districts: ["BUKIT RAYA", "KATINGAN HILIR", "KATINGAN KUALA", "KATINGAN TENGAH", "MARIKIT", "PETAK MALAI", "PULAU MALAN", "SANAMAN MANTIKEI", "TASIK PAYAWAN", "TEWANG SANGALANG GARING", "KAMIPANG"] },
            { name: "KAB. KOTAWARINGIN BARAT", districts: ["ARUT SELATAN", "ARUT UTARA", "KOTAWARINGIN LAMA", "KUMAI", "PANGKALAN BANTENG", "PANGKALAN LADA"] },
            { name: "KAB. KOTAWARINGIN TIMUR", districts: ["ANTANG KALANG", "BAAMANG", "BUKIT SANTUAI", "CEMPAGA", "CEMPAGA HULU", "KOTA BESI", "MENTAWA BARU KETAPANG", "MENTAYA HILIR SELATAN", "MENTAYA HILIR UTARA", "MENTAYA HULU", "PARENGGEAN", "PULAU HANAUT", "SERANAU", "TELAWANG", "TELAGA ANTANG", "TELUK SAMPIT", "TUALAN HULU"] },
            { name: "KAB. LAMANDAU", districts: ["BATANGKAWA", "BELANTIKAN RAYA", "BULIK", "BULIK TIMUR", "DELANG", "LAMANDAU", "MENTHOBI RAYA", "SEMATU JAYA"] },
            { name: "KAB. MURUNG RAYA", districts: ["BARITO TUHU RAYA", "LAUNG TUHUP", "MURUNG", "PERMATA INTAN", "SUMBER BARITO", "SUNGAI BABUAT", "TANAH SIANG", "TANAH SIANG SELATAN", "ULU TUMEH", "URAP"] },
            { name: "KAB. PULANG PISAU", districts: ["BANAMA TINGANG", "JABIREN RAYA", "KAHAYAN HILIR", "KAHAYAN KUALA", "KAHAYAN TENGAH", "MALIKU", "PANDIH BATU", "SEBANGAU KUALA"] },
            { name: "KAB. SUKAMARA", districts: ["BALAI RIAM", "JELAI", "PANTAI LUNCI", "PERMATA KECUBUNG", "SUKAMARA"] },
            { name: "KAB. SERUYAN", districts: ["BATU AMPAR", "DANAU SEMBULUH", "HANAU", "SERUYAN HILIR", "SERUYAN HILIR TIMUR", "SERUYAN HULU", "SERUYAN RAYA", "SERUYAN TENGAH", "SULING TAMBUN"] }
        ]
    },
    {
        name: "KALIMANTAN TIMUR",
        regencies: [
            { name: "KOTA BALIKPAPAN", districts: ["BALIKPAPAN BARAT", "BALIKPAPAN KOTA", "BALIKPAPAN SELATAN", "BALIKPAPAN TENGAH", "BALIKPAPAN TIMUR", "BALIKPAPAN UTARA"] },
            { name: "KOTA BONTANG", districts: ["BONTANG BARAT", "BONTANG SELATAN", "BONTANG UTARA"] },
            { name: "KOTA SAMARINDA", districts: ["LOA JANAN ILIR", "PALARAN", "SAMARINDA ILIR", "SAMARinda KOTA", "SAMARINDA SEBERANG", "SAMARINDA ULU", "SAMBUTAN", "SUNGAI KUNJANG", "SUNGAI PINANG"] },
            { name: "KAB. BERAU", districts: ["BATU PUTIH", "BIDUK-BIDUK", "GUNUNG TABUR", "KELAY", "MARATUA", "PULAU DERAWAN", "SAMBALIUNG", "SEGAH", "TABALAR", "TALISAYAN", "TANJUNG REDEB", "TELUK BAYUR", "BIATAN"] },
            { name: "KAB. KUTAI BARAT", districts: ["BARONG TONGKOK", "BENTIAN BESAR", "BONGAN", "DAMAI", "JEMPANG", "LINGGANG BIGUNG", "LONG IRAM", "MELAK", "MOOK MANAAR BULATN", "MUARA LAWA", "MUARA PAHU", "NYUATAN", "PENYINGGAHAN", "SEKOLAQ DARAT", "SILUQ NGURAI", "TERING"] },
            { name: "KAB. KUTAI KARTANEGARA", districts: ["ANGGANA", "KEMBANG JANGGUT", "KENOHAN", "KOTA BANGUN", "LOA JANAN", "LOA KULU", "MARANG KAYU", "MUARA BADAK", "MUARA JAWA", "MUARA KAMAN", "MUARA MUNTAI", "MUARA WIS", "SANGA-SANGA", "SEBULU", "SEMBOJA", "TABANG", "TENGGARONG", "TENGGARONG SEBERANG"] },
            { name: "KAB. KUTAI TIMUR", districts: ["BATU AMPAR", "BENGALON", "BUSANG", "KALiorang", "KARANGAN", "KAUBUN", "KOMBENG", "LONG MESANGAT", "MUARA ANCALONG", "MUARA WAHAU", "RANTAU PULUNG", "SANDARAN", "SANGATTA SELATAN", "SANGATTA UTARA", "SANGKULIRANG", "TELEN", "TELUK PANDAN"] },
            { name: "KAB. MAHAKAM ULU", districts: ["LAHAM", "LONG APARI", "LONG BAGUN", "LONG HUBUNG", "LONG PAHANGAI"] },
            { name: "KAB. PASER", districts: ["BATU ENGAU", "BATU SOPANG", "KUARO", "LONG IKIS", "LONG KALI", "MUARA KOMAM", "MUARA SAMU", "PASIR BELENGKONG", "TANAH GROGOT", "TANJUNG HARAPAN"] },
            { name: "KAB. PENAJAM PASER UTARA", districts: ["BABULU", "PENAJAM", "SEPAKU", "WARU"] }
        ]
    },
    {
        name: "KALIMANTAN BARAT",
        regencies: [
            { name: "KOTA PONTIANAK", districts: ["PONTIANAK BARAT", "PONTIANAK KOTA", "PONTIANAK SELATAN", "PONTIANAK TENGGARA", "PONTIANAK TIMUR", "PONTIANAK UTARA"] },
            { name: "KOTA SINGKAWANG", districts: ["SINGKAWANG BARAT", "SINGKAWANG SELATAN", "SINGKAWANG TENGAH", "SINGKAWANG TIMUR", "SINGKAWANG UTARA"] },
            { name: "KAB. BENGKAYANG", districts: ["BENGKAYANG", "CAPKALA", "JAGOI BABANG", "LEDO", "LUMAR", "MONTERADO", "SAMALANTAN", "SANGGAU LEDO", "SELUAS", "SIDING", "SUTI SEMARANG", "TERIAK", "SUNGAI BETUNG", "SUNGAI RAYA KEPULAUAN", "LEMBAH BAWANG"] },
            { name: "KAB. KAPUAS HULU", districts: ["BADAU", "BATANG LUPAR", "BIKA", "BOYAN TANJUNG", "BUNUT HILIR", "BUNUT HULU", "EMBALOH HILIR", "EMBALOH HULU", "EMANGAU", "HULU GURUNG", "KALIS", "MENTEBAH", "PENGKADAN", "PUPUS", "PUTUSSIBAU SELATAN", "PUTUSSIBAU UTARA", "SEBERUANG", "SELIMBAU", "SEMITAU", "SILAT HILIR", "SILAT HULU", "SUHAID", "TEPUAI"] },
            { name: "KAB. KAYONG UTARA", districts: ["PULAU MAYA", "SEPANJANG", "SIMPANG HILIR", "SUKADANA", "TELUK BATANG", "KEPULAUAN KARIMATA"] },
            { name: "KAB. KETAPANG", districts: ["AIR UPAS", "BENUA KAYONG", "DELTA PAWAN", "HULU SUNGAI", "JELAI HULU", "KENDAWANGAN", "MANIS MATA", "MARAU", "MATAN HILIR SELATAN", "MATAN HILIR UTARA", "MUARA PAWAN", "NANGA TAYAP", "PEMAHAN", "SANDAI", "SIMPANG DUA", "SIMPANG HULU", "SUNGAI LAUR", "SUNGAI MELAYU RAYAK", "TUMBANG TITI", "SINGKUP"] },
            { name: "KAB. KUBU RAYA", districts: ["AMBAWANG", "BATU AMPAR", "KUALA MANDOR-B", "KUBU", "RASAU JAYA", "SUNGAI AMBAWANG", "SUNGAI KAKAP", "SUNGAI RAYA", "TELUK PAKEDAI", "TERENTANG"] },
            { name: "KAB. LANDAK", districts: ["AIR BESAR", "JELIMPO", "KUALA BEHE", "MANDOR", "MEMPAWAH HULU", "MENJALIN", "MENYUKE", "MERANTI", "NGABANG", "SEBANGKI", "SENGAH TEMILA", "SOMPAK", "BANYUKE HULU"] },
            { name: "KAB. MELAWI", districts: ["BELIMBING", "BELIMBING HULU", "ELLA HILIR", "MENUKUNG", "NANGA PINOH", "PINOH SELATAN", "PINOH UTARA", "SAYAN", "SOKAN", "TANAH PINOH", "TANAH PINOH BARAT"] },
            { name: "KAB. MEMPAWAH", districts: ["ANJONGAN", "MEMPAWAH HILIR", "MEMPAWAH TIMUR", "SADANIANG", "SEGEDONG", "SUNGAI KUNYIT", "SUNGAI PINYUH", "TOHO"] },
            { name: "KAB. SAMBAS", districts: ["GALING", "JAWAI", "JAWAI SELATAN", "PALOH", "SAJAD", "SAJINGAN BESAR", "SALATIGA", "SAMBAS", "SEBAWI", "SELAKAU", "SELAKAU TIMUR", "SEMBAWA", "SEMPARUK", "SUBAH", "TANGARAN", "TEBAS", "TEKARANG", "TELUK KERAMAT"] },
            { name: "KAB. SANGGAU", districts: ["BALAI", "BEDUAI", "BONTI", "ENTIKONG", "JANGKANG", "KAPUAS", "KEMBAYAN", "MELIAU", "MUKOK", "NOYAN", "PARINDU", "SANGGAU", "SEKAYAM", "TAYAN HILIR", "TAYAN HULU", "TOBA"] },
            { name: "KAB. SEKADAU", districts: ["BELITANG", "BELITANG HILIR", "BELITANG HULU", "NANGA MAHAP", "NANGA TAMAN", "SEKADAU HILIR", "SEKADAU HULU"] },
            { name: "KAB. SINTANG", districts: ["AMBALAU", "BINJAI HULU", "DEDAI", "KAYAN HILIR", "KAYAN HULU", "KELAM PERMAI", "KETUNGAU HILIR", "KETUNGAU HULU", "KETUNGAU TENGAH", "SINTANG", "SEPauk", "SUNGAI TEBELIAN", "SERAWAI", "TEMPUNAK"] }
        ]
    },
    {
        name: "KALIMANTAN UTARA",
        regencies: [
            { name: "KOTA TARAKAN", districts: ["TARAKAN BARAT", "TARAKAN TENGAH", "TARAKAN TIMUR", "TARAKAN UTARA"] },
            { name: "KAB. BULUNGAN", districts: ["BUNYU", "PESO", "PESO HILIR", "SEKATAK", "TANJUNG PALAS", "TANJUNG PALAS BARAT", "TANJUNG PALAS TENGAH", "TANJUNG PALAS TIMUR", "TANJUNG PALAS UTARA", "TANJUNG SELOR"] },
            { name: "KAB. MALINAU", districts: ["BAHAU HULU", "KAYAN HILIR", "KAYAN HULU", "KAYAN SELATAN", "MALINAU BARAT", "MALINAU KOTA", "MALINAU SELATAN", "MALINAU SELATAN HILIR", "MALINAU SELATAN HULU", "MALINAU UTARA", "MENTARANG", "MENTARANG HULU", "PUJUNGAN", "SUNGAI BOH", "SUNGAI TUBU"] },
            { name: "KAB. NUNUKAN", districts: ["KRAYAN", "KRAYAN BARAT", "KRAYAN SELATAN", "KRAYAN TENGAH", "KRAYAN TIMUR", "LUMBIS", "LUMBIS OGONG", "NUNUKAN", "NUNUKAN SELATAN", "SEBATIK", "SEBATIK BARAT", "SEBATIK TENGAH", "SEBATIK TIMUR", "SEBATIK UTARA", "SEBUKU", "SEI MENGGARIS", "SEMBAKUNG", "SEMBAKUNG ATULAI", "TULIN ONSOI"] },
            { name: "KAB. TANA TIDUNG", districts: ["BETAYAU", "MURUK RIAN", "SESAYAP", "SESAYAP HILIR", "TANA LIA"] }
        ]
    }
];
